pkg/bgp/bgp-capability.go, pkg/bgp/bgp-information-tlv.go, pkg/bgp/bgp-open.go, pkg/bmp/message.go, pkg/bmp/per-peer-header.go, pkg/gobmpsrv/gobmpsrv.go, pkg/kafkaproducer/kafka-messages.go, pkg/kafkaproducer/kafka-producer.go, pkg/parser/parser.go
=> initial peer up conversion into kafka message

pkg/bgp/bgp-update.go, pkg/message/base-nlri.go, pkg/message/ls-link.go, pkg/message/ls-node.go, pkg/message/types.go, pkg/sr/sr-prefixsid.go
=> convert as_path from string into slice

deployment/gobmp-topology.yaml, go.mod, pkg/bgp/bgp-update.go, pkg/bgp/bgp-update_test.go, pkg/bgp/extended-community.go, pkg/bgp/go.mod, pkg/bgp/go.sum, pkg/bgp/mp-reach-nlri.go, pkg/bmp/consts.go, pkg/kafka/kafka-publisher.go, pkg/l3vpn/go.mod, pkg/l3vpn/l3-vpn.go, pkg/l3vpn/l3vpn_test.go, pkg/message/base-nlri.go, pkg/message/l3-vpn.go, pkg/message/l3vpn.go, pkg/message/route-monitor.go, pkg/message/types.go
=> Initial type definitions for l3vpn

cmd/topology/go.mod, cmd/topology/go.sum, pkg/topology/arangodb/arangodb.go, pkg/topology/database/arango.go, pkg/topology/database/database.go, pkg/topology/database/epe_link.go, pkg/topology/database/epe_node.go, pkg/topology/database/epe_prefix.go, pkg/topology/database/go.mod, pkg/topology/database/helpers.go, pkg/topology/database/l3vpn_node.go, pkg/topology/database/l3vpn_prefix.go, pkg/topology/database/ls_link.go, pkg/topology/database/ls_node.go, pkg/topology/database/object.go, pkg/topology/database/routers.go, pkg/topology/mockdb/mockdb.go, pkg/topology/processor/processor.go
=> Borrow existing arango database funcs

cmd/topology/go.mod, pkg/message/route-monitor.go, pkg/topology/arangodb/arangodb.go, pkg/topology/arangodb/sample-peer.go, pkg/topology/database/arango.go, pkg/topology/database/epe_node.go, pkg/topology/kafkamessenger/kafkamessenger.go, pkg/topology/processor/processor.go
Adjust min bytes to 0 for Kafka reader to immediately receive Kafka message
=> Debug kafka topic read

pkg/bmp/go.mod, pkg/message/go.mod, pkg/tools/go.mod
=> Change modules names for externally used packages

pkg/base/go.mod, pkg/bgp/go.mod, pkg/bgpls/go.mod, pkg/evpn/go.mod, pkg/l3vpn/go.mod, pkg/ls/go.mod, pkg/sr/go.mod, pkg/srv6/go.mod
=> more package renames

pkg/kafka/go.mod, pkg/parser/go.mod, pkg/pub/go.mod
=> even more renames

pkg/base/link-nlri.go, pkg/base/node-nlri.go, pkg/base/prefix-nlri.go, pkg/bgp/mp-reach-nlri.go, pkg/bgp/mp-unreach-nlri.go, pkg/bgpls/bgpls-nlri.go, pkg/evpn/evpn.go, pkg/l3vpn/l3-vpn.go, pkg/ls/ls-nlri71.go, pkg/srv6/srv6-sidnlri.go, pkg/tools/tools.go, pkg/unicast/unicast.go
=> Add protection for the case when NLRI length is 0

cmd/topology/go.mod, cmd/topology/go.sum, pkg/topology/kafkamessenger/kafkamessenger.go
=> add topics to sample topology code

go.mod, pkg/bgp/bgp-update_test.go, pkg/bgp/go.mod, pkg/bgp/go.sum, pkg/message/l3-vpn.go
=> remove duplication for extended communities

cmd/topology/go.mod, cmd/topology/go.sum, go.mod
=> cleaning up dependency for v0.0.1-alpha.01

go.mod, pkg/base/go.mod, pkg/gobmpsrv/go.mod
=> more dependecies

cmd/topology/go.mod, cmd/topology/go.sum, go.mod, pkg/bgp/go.mod, pkg/bgp/go.sum, pkg/l3vpn/go.mod
=> hopefully last one

cmd/topology/go.mod, cmd/topology/go.sum
=> finalize topology's go.mod

pkg/message/l3-vpn.go, pkg/message/ls-node.go, pkg/message/ls-prefix.go, pkg/message/ls-srv6-sid.go
=> remove leftover comments

pkg/topology/processor/processor.go
=> Add missing types of messages

.travis.yml, pkg/bgp/bgp-update.go, pkg/prefixsid/go.mod, pkg/prefixsid/go.sum, pkg/prefixsid/prefixsid_test.go, pkg/tools/go.sum
=> Fix unit tests

.travis.yml, build/Dockerfile, pkg/prefixsid/prefixsid_test.go, pkg/srv6/srv6-l3-service.go, pkg/srv6/srv6-l3-service_test.go
=> refactor srv6 l3 struct and test

pkg/prefixsid/prefixsid_test.go, pkg/srv6/srv6-l3-service.go, pkg/srv6/srv6-l3-service_test.go
=> Attempt to make srv6 structure more flat

pkg/bgpls/bgpls-nlri.go, pkg/message/ls-link.go, pkg/message/types.go, pkg/srv6/srv6-endxsidtlv.go
=> Add ENDXSID to ls_link message

pkg/bgpls/bgpls-nlri.go, pkg/ls/ls-nlri71.go, pkg/message/process-mp-update.go, pkg/message/types.go, pkg/sr/sr-local-block-tlv.go, pkg/sr/sr-local-block.go, pkg/sr/sr_test.go
=> convert sr block into object

pkg/bmp/per-peer-header.go, pkg/message/peer.go
=> refactor per peer distinguisher

pkg/srv6/srv6-l3-service.go
=> Addressing issue #82

pkg/bmp/route-monitor.go
=> fix panic for route refresh message

pkg/bgpls/bgpls-nlri.go, pkg/message/types.go
=> Return slice of PRefixSIDs for 1158 attribute

pkg/bgp/extended-community-const.go, pkg/bgp/extended-community.go, pkg/bgp/extended_community_test.go
This PR refactors Extended Community processing to make it more modular and extensible
=> ext community refactor

Makefile, deployment/gobmp-standalone.yaml, deployment/gobmp-topology.yaml, pkg/base/link-nlri.go, pkg/base/node-nlri.go, pkg/base/prefix-attr-flags.go, pkg/base/prefix-nlri.go, pkg/bgpls/bgpls-nlri.go, pkg/message/ls-link.go, pkg/message/ls-node.go, pkg/message/ls-prefix.go, pkg/message/process-mp-update.go, pkg/message/types.go, pkg/sr/sr-prefixsid.go, pkg/srv6/srv6-sidnlri.go, pkg/tools/tools.go, pkg/topology/arangodb/arangodb.go
This PR starts refactoring Flags in different object, to make them Protocol ID specific.
=> Flags interface

deployment/gobmp-topology.yaml, pkg/base/prefix-attr-flags.go, pkg/bgpls/bgpls-nlri.go, pkg/bgpls/bgpls-tlv.go, pkg/message/conversion.go, pkg/message/ls-node.go, pkg/message/ls-prefix.go, pkg/message/types.go, pkg/sr/sr-capability.go, pkg/sr/sr-prefixsid.go, pkg/sr/sr_test.go
=> Add Protocol ID dependent Flags interface to SR Capability

pkg/bgp/bgp-base-attributes.go
=> fix panic when as_path is 0

pkg/base/link-nlri.go, pkg/base/node-nlri.go, pkg/base/prefix-nlri.go, pkg/message/ls-link.go, pkg/message/ls-node.go, pkg/message/ls-prefix.go, pkg/message/ls-srv6-sid.go, pkg/message/types.go, pkg/srv6/srv6-sidnlri.go
=> add domain id

cmd/gobmp/gobmp_test.go, pkg/bgp/bgp-capability.go, pkg/bgp/bgp-information-tlv.go, pkg/bgp/bgp-open.go, pkg/bgp/bgp-open_test.go, pkg/message/peer.go, pkg/message/types.go
Refactor bgp capabilities from CSV string into a structure for easier consumption by the client software.
=> Structured capabilities

pkg/message/ls-prefix.go, pkg/message/types.go
=> add population of ospf route type field

pkg/message/process-mp-update.go, pkg/message/srpolicy.go, pkg/srpolicy/srpolicy-nlri_test.go, pkg/srpolicy/srpolicy-tlv.go
=> Fix for issue #131

pkg/bgpls/flexalgo.go, pkg/bgpls/flexalgo_test.go
I think this is a better representation of the optional FAD attributes. Thanks.
=> Resolve Flex-Algo Definition SubTLVs

pkg/base/label.go
=> Add BoS bit cleanup

pkg/bgp/extended-community-const.go, pkg/bgp/extended-community.go, pkg/bgp/extended_community_test.go, pkg/bgp/mp-nlri.go, pkg/bgp/mp-reach-nlri.go, pkg/bgp/mp-unreach-nlri.go, pkg/bmp/consts.go, pkg/flowspec/flowspec_nlri.go, pkg/flowspec/flowspec_nlri_test.go, pkg/kafka/kafka-publisher.go, pkg/message/flowspec.go, pkg/message/peer.go, pkg/message/process-mp-update.go, pkg/message/types.go
This PR adds initial support to Flowspec afi/safi 1/133. It also adds new flowspec related extended community and sub types processing.
=> Flowspec support part 1

pkg/base/node-descriptor.go, pkg/base/prefix-nlri.go, pkg/bgpls/bgpls-nlri.go, pkg/message/ls-link.go, pkg/message/types.go, pkg/sr/sr-peersid.go
=> add protocol id 7 processing

pkg/bgpls/bgpls-nlri.go, pkg/message/ls-prefix.go, pkg/message/types.go, pkg/sr/sr-adjacencysid.go, pkg/sr/sr-capabilitiy-tlv.go, pkg/sr/sr-capability.go, pkg/sr/sr-prefixsid.go, pkg/sr/sr-sid-tlv.go, pkg/sr/sr_test.go
=> Closes #142

pkg/message/ls-prefix.go
=> make sure area id gets populated even on delete

pkg/base/node-descriptor.go, pkg/base/node-nlri_test.go
=> fix decoding igp router id

pkg/bgpls/flexalgo.go
Closes: #151 
@fclad please review.
=> Decode FADSubTLV Flags

pkg/bgpls/bgp-ls-prefix.go, pkg/bgpls/bgpls-igp.go, pkg/message/ls-prefix.go, pkg/message/types.go
closes: #156 
@fclad Please review
=> add structure for IGP Flag

pkg/bgpls/bgpls-nlri.go, pkg/bgpls/bgpls-srv6-policy-state.go, pkg/bgpls/prefix-attr-tlv.go, pkg/message/ls-prefix.go, pkg/message/ls-prefix_test.go, pkg/message/types.go
=> Prefix attr tlvs and flags

pkg/srv6/srv6-locator.go
=> srv6 locator's flag object

pkg/base/multitopologyidentifier.go, pkg/srv6/srv6-endxsidtlv.go, pkg/srv6/srv6-sidnlri_test.go
=> refactor flags in a separate structure

pkg/bgpls/bgpls-nlri.go, pkg/message/ls-node.go, pkg/sr/sr-capability.go, pkg/sr/sr-peersid.go, pkg/sr/sr_test.go, pkg/srv6/srv6-bgp-peer-node-sid-tlv.go
=> Refactor SR peer flags

pkg/sr/sr-capability.go
=> Fix Panic interface conversion: sr.CapabilityFlags

pkg/srv6/srv6-capabilities.go, pkg/srv6/srv6-l3-service.go
=> Process Capability Flag

pkg/bgpls/bgpls-nlri.go, pkg/bgpls/node-attr-tlv.go, pkg/message/ls-node.go, pkg/message/types.go
=> address issue #169

pkg/sr/sr-adjacencysid.go, pkg/sr/sr-peersid.go, pkg/sr/sr-peersid_test.go
=> issue #171 and SID to uint32

pkg/sr/sr-adjacencysid.go
=> fix isis sid tag in Unmarshal func

pkg/bmp/per-peer-header.go
=> Change timestamp format for published messages

cmd/gobmp/gobmp.go, pkg/dumper/dumper.go, pkg/filer/filer.go
=> add error check for all types of publishers

pkg/bgpls/bgpls-nlri.go, pkg/message/types.go
=> change to return single instance of locator

pkg/srv6/srv6-endxsidtlv_test.go, pkg/srv6/srv6-subtlv.go
=> Incorrect offset calculation in SRv6 SubTLV 

pkg/srv6/srv6-endxsidtlv.go
=> remove omit empty tag so int of value 0 are visible in json

pkg/base/label.go, pkg/bgp/extended-community.go, pkg/bgp/extended_community_test.go, pkg/bmp/peer-up.go, pkg/bmp/per-peer-header.go, pkg/bmp/per-peer-header_test.go, pkg/evpn/evpn.go, pkg/kafka/kafka-publisher.go, pkg/message/bmpstats.go, pkg/message/evpn.go, pkg/message/producer.go, pkg/message/types.go, pkg/parser/parser.go
- Added Peer-Type 3 (local-rib) RFC 9069.
- Added BMP statistic messages parsing.
- Updated Ext Community RMAC string represantation.
- Added some required fields to EVPN messages.
=> Couple of improvements for evpn

CHANGELOG.md, pkg/bgpls/bgpls-nlri.go
See https://github.com/sbezverk/gobmp/issues/215
=> Index unresv bw slice

pkg/message/base-nlri.go, pkg/message/evpn.go, pkg/message/flowspec.go, pkg/message/l3-vpn.go, pkg/message/mp-unicast.go, pkg/message/srpolicy.go, pkg/message/types.go
=> change originAS to uint32
